regen.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -673,6 +673,7 @@ OBJEXT
 CPP
 GREP
 EGREP
+GENCAT
 CC_FOR_GETHOST
 LIBICONV
 LTLIBICONV
@@ -1267,6 +1268,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-rpath         do not hardcode runtime library paths
   --disable-nls           Disable NLS support
+  --disable-nls-catalogs  Disable NLS catalog support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3544,6 +3546,47 @@ echo "${ECHO_T}$ac_cv_prog_gcc_traditional" >&6; }
 fi
 
 
+# Extract the first word of "gencat", so it can be a program name with args.
+set dummy gencat; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GENCAT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GENCAT in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GENCAT="$GENCAT" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GENCAT="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GENCAT=$ac_cv_path_GENCAT
+if test -n "$GENCAT"; then
+  { echo "$as_me:$LINENO: result: $GENCAT" >&5
+echo "${ECHO_T}$GENCAT" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 if test "x${cross_compiling}" = xyes ; then
   CC_FOR_GETHOST="cc"
 else
@@ -5086,7 +5129,8 @@ done
 
 
 
-for ac_header in auth.h crypt.h inttypes.h shadow.h stdint.h utmp.h utmpx.h
+
+for ac_header in auth.h crypt.h inttypes.h paths.h shadow.h stdint.h utmp.h utmpx.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -8238,6 +8282,92 @@ else
   have_setlocale=no
 fi
 
+{ echo "$as_me:$LINENO: checking for catgets" >&5
+echo $ECHO_N "checking for catgets... $ECHO_C" >&6; }
+if test "${ac_cv_func_catgets+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define catgets to an innocuous variant, in case <limits.h> declares catgets.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define catgets innocuous_catgets
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char catgets (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef catgets
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char catgets ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_catgets || defined __stub___catgets
+choke me
+#endif
+
+int
+main ()
+{
+return catgets ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_catgets=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_catgets=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_catgets" >&5
+echo "${ECHO_T}$ac_cv_func_catgets" >&6; }
+if test $ac_cv_func_catgets = yes; then
+  have_catgets=yes
+else
+  have_catgets=no
+fi
 
 
 
@@ -8258,7 +8388,7 @@ fi
 
 
 
-for ac_func in catgets dup2 getauthid getcwd gethostname getpwent 	getutent mallinfo memmove memset mkstemp nice nl_langinfo sbrk 	setpgid setpriority strerror strstr sysconf wcwidth
+for ac_func in dup2 getauthid getcwd gethostname getpwent 	getutent mallinfo memmove memset mkstemp nice nl_langinfo sbrk 	setpgid setpriority strerror strstr sysconf wcwidth
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -8635,6 +8765,23 @@ fi
 
 cat >>confdefs.h <<\_ACEOF
 #define NLS 1
+_ACEOF
+
+  fi
+fi
+
+if test "x$enable_nls" != xno -a "$have_catgets" != no -a -n "$GENCAT" ; then
+  # Check whether --enable-nls-catalogs was given.
+if test "${enable_nls_catalogs+set}" = set; then
+  enableval=$enable_nls_catalogs;
+else
+  enable_nls_catalogs=yes
+fi
+
+  if test "x$enable_nls_catalogs" != xno; then
+
+cat >>confdefs.h <<\_ACEOF
+#define NLS_CATALOGS 1
 _ACEOF
 
   fi
@@ -9493,6 +9640,7 @@ OBJEXT!$OBJEXT$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+GENCAT!$GENCAT$ac_delim
 CC_FOR_GETHOST!$CC_FOR_GETHOST$ac_delim
 LIBICONV!$LIBICONV$ac_delim
 LTLIBICONV!$LTLIBICONV$ac_delim
@@ -9503,7 +9651,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 66; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 67; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
